"use client";

/* eslint-disable react/no-unescaped-entities */
export function Legal() {
  return (
    <div className="min-h-screen py-24">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <h1 className="text-5xl font-bold mb-6">
          <span className="text-[#00FF94]">Legal</span> Information
        </h1>
        <p className="text-[#A0A0A0] mb-12">Company & compliance information for <strong className="text-white">morra.store</strong></p>

        <div className="space-y-8 text-[#A0A0A0]">
          <section>
            <h2 className="text-2xl font-bold text-white mb-4">Company Information</h2>
            <div className="p-6 rounded-2xl bg-[#121212] border border-[#00FF94]/20">
              <p className="leading-relaxed mb-2">
                <strong className="text-white">Company Name:</strong> MORRA Inc.
              </p>
              <p className="leading-relaxed mb-2">
                <strong className="text-white">Registration:</strong> [Registration Number]
              </p>
              <p className="leading-relaxed">
                <strong className="text-white">Address:</strong> [Company Address]
              </p>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">Disclaimers</h2>
            <div className="space-y-4">
              <div className="p-6 rounded-2xl bg-[#121212] border border-[#00FF94]/20">
                <h3 className="text-lg font-semibold text-white mb-2">AI-Generated Content</h3>
                <p className="leading-relaxed">
                  Content generated by MORRA's AI tools on morra.store is provided as creative assistance and should be reviewed
                  before use. We do not guarantee the accuracy, quality, or suitability of AI-generated content for
                  any specific purpose. AI outputs may contain errors, biases, or inappropriate content. Users are
                  solely responsible for reviewing and using AI-generated content appropriately.
                </p>
              </div>

              <div className="p-6 rounded-2xl bg-[#121212] border border-[#00FF94]/20">
                <h3 className="text-lg font-semibold text-white mb-2">Financial Payouts</h3>
                <p className="leading-relaxed">
                  MORRA's referral program may allow users to earn revenue share from referred subscriptions. However,
                  earnings are not guaranteed and depend on referred users maintaining active subscriptions. We are
                  not responsible for tax obligations related to your earnings, you must report and pay any applicable
                  taxes yourself. Payouts, where offered, are processed through Stripe Connect and are subject to Stripe's terms and
                  processing times.
                </p>
              </div>

              <div className="p-6 rounded-2xl bg-[#121212] border border-[#00FF94]/20">
                <h3 className="text-lg font-semibold text-white mb-2">Platform Limitations</h3>
                <p className="leading-relaxed">
                  morra.store is provided "as is" and may experience downtime, bugs, or service interruptions. We do not
                  guarantee uninterrupted access or error-free operation. Credit usage and generation limits are
                  enforced and may be adjusted based on system load and abuse prevention measures.
                </p>
              </div>

              <div className="p-6 rounded-2xl bg-[#121212] border border-[#00FF94]/20">
                <h3 className="text-lg font-semibold text-white mb-2">Professional Advice</h3>
                <p className="leading-relaxed">
                  MORRA does not provide legal, financial, or professional advice. Content generated through our
                  platform should not be considered as such. Consult with qualified professionals for specific advice.
                </p>
              </div>

              <div className="p-6 rounded-2xl bg-[#121212] border border-[#00FF94]/20">
                <h3 className="text-lg font-semibold text-white mb-2">Third-Party Links</h3>
                <p className="leading-relaxed">
                  Our platform may contain links to third-party websites or services (such as Instagram for artist
                  connections, or Stripe for payments). We are not responsible for the content, privacy practices, or
                  terms of these external sites.
                </p>
              </div>

              <div className="p-6 rounded-2xl bg-[#121212] border border-[#00FF94]/20">
                <h3 className="text-lg font-semibold text-white mb-2">Not for PII Collection</h3>
                <p className="leading-relaxed">
                  MORRA is not designed or intended for collecting or securing personally identifiable information (PII)
                  or sensitive user data about others. Do not use morra.store to collect, store, or process personal information about
                  others in violation of law. If your use case requires handling PII, use appropriate, compliant systems designed for that purpose.
                </p>
              </div>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">Intellectual Property</h2>
            <p className="leading-relaxed mb-4">
              All aspects of the MORRA platform, including but not limited to design, code, logos, and AI models,
              are protected by copyright, trademark, and other intellectual property laws.
            </p>
            <p className="leading-relaxed">
              Users retain full ownership of content they create using MORRA. We do not claim any rights to user-generated
              content or creative outputs, subject to our Terms of Service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">DMCA & Copyright</h2>
            <p className="leading-relaxed mb-4">
              MORRA respects intellectual property rights. Users are responsible for ensuring their inputs don't infringe on others' copyrights.
            </p>
            <p className="leading-relaxed">
              AI-generated outputs are provided as creative assistance. You are responsible for reviewing content
              before use to ensure it doesn't violate any copyright laws.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">Data Protection & GDPR</h2>
            <p className="leading-relaxed mb-4">
              MORRA complies with applicable data protection regulations for users of morra.store, including GDPR where it applies.
              You may have rights regarding your personal data:
            </p>
            <ul className="space-y-2 list-disc list-inside">
              <li>Right to access your data</li>
              <li>Right to correction of inaccurate data</li>
              <li>Right to deletion ("right to be forgotten")</li>
              <li>Right to data portability</li>
              <li>Right to object to processing</li>
            </ul>
            <p className="leading-relaxed mt-4">
              To exercise these rights, manage your data through your account settings or contact us via the{" "}
              <span className="text-[#00FF94] font-semibold">AI assistant</span> on morra.store.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">Liability Limitations</h2>
            <p className="leading-relaxed">
              To the fullest extent permitted by law, MORRA and its founders, employees, and partners shall not be
              liable for any indirect, incidental, special, consequential, or punitive damages resulting from your
              use or inability to use the service. See the Terms of Service on morra.store for further limitations.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">Dispute Resolution</h2>
            <p className="leading-relaxed">
              Any disputes arising from your use of morra.store will first be attempted to be resolved through good-faith
              negotiation. If unsuccessful, disputes may be resolved through binding arbitration in accordance with
              the rules of [Arbitration Body], as set forth in our Terms of Service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">Legal & compliance contact</h2>
            <div className="p-6 rounded-2xl bg-gradient-to-r from-[#00FF94]/10 to-[#9BFF00]/10 border border-[#00FF94]/30">
              <p className="leading-relaxed">
                For legal, compliance, or policy questions, users can contact us via the <strong className="text-white">AI assistant</strong> on <strong className="text-white">morra.store</strong>. We do not publish a legal email for general support.
              </p>
            </div>
          </section>
        </div>
      </div>
    </div>
  );
}
